name: Moi Design Blog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6ba00'
    - '#e3cbd9'
    - '#aa94a9'
    - '#f9b2b8'
    - '#c29043'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
