name: Moi Design Blog
favicon: null
layout_spectrum: 0.04953282489441335
typography_spectrum: 0.06552805285900831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2834431903902441
  lightness: 0.17133745597675443
  saturation: 0.7132499313447624
  rhythmicContrast: 0.11111427727155387
purpose: []
